import{meals}from'./data.js';import{addHistory,clearHistory,getHistory,getSetting,setSetting}from'./db.js';import{countTags,healthNudge,recommendMeal,recommendationReason,scaleIngredients}from'./recommender.js';
const $=id=>document.getElementById(id);const state={people:2,history:[],current:null,mode:'default',excluded:[]};let deferredInstallPrompt=null;
function formatAmount(value){return Number.isInteger(value)?String(value):String(value).replace('.5','٫۵').replace('.25','٫۲۵').replace('.75','٫۷۵')}
function updatePeopleUI(){$('peopleCount').textContent=state.people;$('peopleLabel').textContent=`${state.people} نفر`;if(state.current)renderSuggestion(state.current)}
async function changePeople(delta){state.people=Math.min(12,Math.max(1,state.people+delta));updatePeopleUI();await setSetting('people',state.people)}
function renderSuggestion(meal){state.current=meal;$('suggestionCard').classList.remove('hidden');$('mealName').textContent=meal.name;$('mealEmoji').textContent=meal.emoji;$('mealMeta').textContent=`حدود ${meal.minutes} دقیقه • برای ${state.people} نفر`;$('suggestionReason').textContent=recommendationReason(meal,state.history,meals,state.mode);$('ingredientsList').innerHTML=scaleIngredients(meal.ingredients,state.people).map(i=>`<li><span>${i.name}</span><strong>${formatAmount(i.amount)} ${i.unit}</strong></li>`).join('');$('recipeList').innerHTML=meal.recipe.map(step=>`<li>${step}</li>`).join('');$('recipeList').classList.add('hidden');$('toggleRecipe').textContent='دستور پخت را نشان بده';$('suggestionCard').scrollIntoView({behavior:'smooth',block:'start'})}
function suggest(mode=state.mode,excludeCurrent=false){state.mode=mode;if(excludeCurrent&&state.current)state.excluded.push(state.current.id);if(state.excluded.length>meals.length-3)state.excluded=[];renderSuggestion(recommendMeal(meals,state.history,state.mode,state.excluded))}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function renderHistory(){const list=$('historyList');if(!state.history.length){list.innerHTML='<p class="empty">هنوز چیزی ثبت نشده.</p>';return}const byId=new Map(meals.map(m=>[m.id,m]));list.innerHTML=state.history.slice(0,10).map(entry=>{const meal=byId.get(entry.mealId),date=new Intl.DateTimeFormat('fa-IR',{month:'short',day:'numeric'}).format(new Date(entry.cookedAt));return`<div class="history-item"><div><p><strong>${meal?.emoji||'🍽️'} ${entry.mealName}</strong></p><small>${entry.people} نفر</small></div><small>${date}</small></div>`}).join('')}
function renderHealth(){$('healthMessage').textContent=healthNudge(state.history,meals);const counts=countTags(state.history,meals),items=[['🐟',counts.fish||0,'ماهی'],['🫘',counts.legume||0,'حبوبات'],['🥬',counts.vegetable||0,'سبزیجات'],['🥩',counts.red_meat||0,'گوشت قرمز']];$('weekStats').innerHTML=items.map(([icon,n,label])=>`<div class="stat"><strong>${icon} ${n}</strong><span>${label}</span></div>`).join('')}
async function acceptCurrent(){if(!state.current)return;await addHistory({mealId:state.current.id,mealName:state.current.name,people:state.people,cookedAt:new Date().toISOString()});state.history=await getHistory();renderHistory();renderHealth();toast('در تاریخچه ثبت شد ✓');state.excluded=[]}
async function initOnboarding(){const configured=await getSetting('onboarded'),savedPeople=await getSetting('people');if(savedPeople)state.people=savedPeople;updatePeopleUI();if(configured)return;const grid=$('onboardingPeople');let chosen=state.people;grid.innerHTML=Array.from({length:8},(_,i)=>i+1).map(n=>`<button type="button" data-people="${n}" class="${n===chosen?'selected':''}">${n}</button>`).join('');grid.addEventListener('click',e=>{const n=Number(e.target.dataset.people);if(!n)return;chosen=n;[...grid.children].forEach(btn=>btn.classList.toggle('selected',Number(btn.dataset.people)===chosen))});$('saveOnboarding').addEventListener('click',async()=>{state.people=chosen;await setSetting('people',chosen);await setSetting('onboarded',true);updatePeopleUI()});$('onboardingDialog').showModal()}
function wireEvents(){$('minusPeople').addEventListener('click',()=>changePeople(-1));$('plusPeople').addEventListener('click',()=>changePeople(1));$('suggestBtn').addEventListener('click',()=>{state.excluded=[];suggest('default')});$('anotherMeal').addEventListener('click',()=>suggest(state.mode,true));$('acceptMeal').addEventListener('click',acceptCurrent);document.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>{state.excluded=[];suggest(btn.dataset.mode)}));$('toggleRecipe').addEventListener('click',()=>{const hidden=$('recipeList').classList.toggle('hidden');$('toggleRecipe').textContent=hidden?'دستور پخت را نشان بده':'دستور پخت را ببند'});$('refreshHealth').addEventListener('click',()=>{renderHealth();toast('بر اساس ۷ روز اخیر به‌روز شد')});$('clearHistory').addEventListener('click',async()=>{if(!confirm('تاریخچه غذاها پاک شود؟'))return;await clearHistory();state.history=[];renderHistory();renderHealth();toast('تاریخچه پاک شد')});window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;$('installBtn').classList.remove('hidden')});$('installBtn').addEventListener('click',async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('installBtn').classList.add('hidden')})}
async function boot(){wireEvents();state.history=await getHistory();await initOnboarding();renderHistory();renderHealth();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')}
boot().catch(error=>{console.error(error);toast('خطا در راه‌اندازی؛ صفحه را دوباره باز کن.')});
