import{meals}from'./data.js';import{addHistory,clearHistory,getHistory,getSetting,setSetting}from'./db.js';import{countTags,healthNudge,recommendMeal,recommendationReason,scaleIngredients}from'./recommender.js';
const $=id=>document.getElementById(id);const state={people:2,history:[],current:null,mode:'default',excluded:[],saving:false};let deferredInstallPrompt=null;
function formatAmount(value){return Number.isInteger(value)?String(value):String(value).replace('.5','٫۵').replace('.25','٫۲۵').replace('.75','٫۷۵')}
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function updatePeopleUI(){$('peopleCount').textContent=state.people;$('peopleLabel').textContent=`${state.people} نفر`;if(state.current)renderSuggestion(state.current,false)}
async function changePeople(delta){state.people=Math.min(12,Math.max(1,state.people+delta));updatePeopleUI();await setSetting('people',state.people)}
function renderSuggestion(meal,scroll=true){state.current=meal;$('suggestionCard').classList.remove('hidden');$('mealName').textContent=meal.name;$('mealEmoji').textContent=meal.emoji;$('mealMeta').textContent=`حدود ${meal.minutes} دقیقه • برای ${state.people} نفر`;$('suggestionReason').textContent=recommendationReason(meal,state.history,meals,state.mode);$('ingredientsList').innerHTML=scaleIngredients(meal.ingredients,state.people).map(i=>`<li><span>${i.name}</span><strong>${formatAmount(i.amount)} ${i.unit}</strong></li>`).join('');$('recipeList').innerHTML=meal.recipe.map(step=>`<li>${step}</li>`).join('');$('recipeList').classList.add('hidden');$('toggleRecipe').textContent='دستور پخت را نشان بده';$('acceptMeal').disabled=false;$('acceptMeal').textContent='این را می‌پزم';if(scroll)$('suggestionCard').scrollIntoView({behavior:'smooth',block:'start'})}
function suggest(mode=state.mode,excludeCurrent=false){state.mode=mode;if(excludeCurrent&&state.current)state.excluded.push(state.current.id);if(state.excluded.length>meals.length-3)state.excluded=[];renderSuggestion(recommendMeal(meals,state.history,state.mode,state.excluded))}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function renderHistory(){const list=$('historyList');if(!state.history.length){list.innerHTML='<p class="empty">هنوز چیزی ثبت نشده.</p>';return}const byId=new Map(meals.map(m=>[m.id,m]));list.innerHTML=state.history.slice(0,10).map(entry=>{const meal=byId.get(entry.mealId),date=new Intl.DateTimeFormat('fa-IR',{month:'short',day:'numeric'}).format(new Date(entry.cookedAt));return`<div class="history-item"><div><p><strong>${meal?.emoji||'🍽️'} ${entry.mealName}</strong></p><small>${entry.people} نفر</small></div><small>${date}</small></div>`}).join('')}
function renderHealth(){$('healthMessage').textContent=healthNudge(state.history,meals);const counts=countTags(state.history,meals),items=[['🐟',counts.fish||0,'ماهی'],['🫘',counts.legume||0,'حبوبات'],['🥬',counts.vegetable||0,'سبزیجات'],['🥩',counts.red_meat||0,'گوشت قرمز']];$('weekStats').innerHTML=items.map(([icon,n,label])=>`<div class="stat"><strong>${icon} ${n}</strong><span>${label}</span></div>`).join('')}
async function acceptCurrent(){if(!state.current||state.saving)return;state.saving=true;const button=$('acceptMeal');button.disabled=true;button.textContent='در حال ثبت…';try{await addHistory({mealId:state.current.id,mealName:state.current.name,people:state.people,cookedAt:new Date().toISOString()});state.history=await getHistory();renderHistory();renderHealth();button.textContent='ثبت شد ✓';toast('در تاریخچه ثبت شد ✓');state.excluded=[]}catch(error){console.error(error);button.disabled=false;button.textContent='این را می‌پزم';toast('ثبت نشد؛ دوباره امتحان کن.')}finally{state.saving=false}}
async function initOnboarding(){const configured=await getSetting('onboarded'),savedPeople=await getSetting('people');if(savedPeople)state.people=savedPeople;updatePeopleUI();if(configured)return;const grid=$('onboardingPeople');let chosen=state.people;grid.innerHTML=Array.from({length:8},(_,i)=>i+1).map(n=>`<button type="button" data-people="${n}" class="${n===chosen?'selected':''}">${n}</button>`).join('');grid.addEventListener('click',e=>{const n=Number(e.target.dataset.people);if(!n)return;chosen=n;[...grid.children].forEach(btn=>btn.classList.toggle('selected',Number(btn.dataset.people)===chosen))});$('onboardingForm').addEventListener('submit',async event=>{event.preventDefault();state.people=chosen;await setSetting('people',chosen);await setSetting('onboarded',true);updatePeopleUI();$('onboardingDialog').close()});$('onboardingDialog').showModal()}
function installHelp(){const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);$('installHelpText').textContent=isiOS?'در Safari دکمه Share را بزن، سپس Add to Home Screen را انتخاب کن.':'از منوی مرورگر گزینه Install app یا Add to Home screen را انتخاب کن.';$('installDialog').showModal()}
async function requestInstall(){if(!deferredInstallPrompt){installHelp();return}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('installBtn').classList.add('hidden')}
function updateNetworkStatus(){const online=navigator.onLine;$('networkStatus').textContent=online?'آنلاین':'آفلاین';$('networkStatus').classList.toggle('offline',!online)}
function wireEvents(){$('minusPeople').addEventListener('click',()=>changePeople(-1));$('plusPeople').addEventListener('click',()=>changePeople(1));$('suggestBtn').addEventListener('click',()=>{state.excluded=[];suggest('default')});$('anotherMeal').addEventListener('click',()=>suggest(state.mode,true));$('acceptMeal').addEventListener('click',acceptCurrent);document.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>{state.excluded=[];suggest(btn.dataset.mode)}));$('toggleRecipe').addEventListener('click',()=>{const hidden=$('recipeList').classList.toggle('hidden');$('toggleRecipe').textContent=hidden?'دستور پخت را نشان بده':'دستور پخت را ببند'});$('refreshHealth').addEventListener('click',()=>{renderHealth();toast('بر اساس ۷ روز اخیر به‌روز شد')});$('clearHistory').addEventListener('click',async()=>{if(!confirm('تاریخچه غذاها پاک شود؟'))return;await clearHistory();state.history=[];renderHistory();renderHealth();toast('تاریخچه پاک شد')});$('installBtn').addEventListener('click',requestInstall);$('closeInstallHelp').addEventListener('click',()=>$('installDialog').close());window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;if(!isStandalone())$('installBtn').classList.remove('hidden')});window.addEventListener('appinstalled',()=>{$('installBtn').classList.add('hidden');toast('اپ نصب شد ✓')});window.addEventListener('online',updateNetworkStatus);window.addEventListener('offline',updateNetworkStatus)}
async function boot(){wireEvents();updateNetworkStatus();if(!isStandalone())$('installBtn').classList.remove('hidden');state.history=await getHistory();await initOnboarding();renderHistory();renderHealth();if('serviceWorker'in navigator){try{const registration=await navigator.serviceWorker.register('./sw.js');registration.update()}catch(error){console.warn('[Food Choice] service worker:',error)}}}
boot().catch(error=>{console.error(error);toast('خطا در راه‌اندازی؛ صفحه را دوباره باز کن.')});
