const DAY=24*60*60*1000;
export function scaleIngredients(ingredients,people,basePeople=4){const factor=people/basePeople;return ingredients.map(([name,amount,unit])=>({name,amount:Math.round(amount*factor*100)/100,unit}))}
export function weekEntries(history,now=new Date()){const cutoff=new Date(now.getTime()-7*DAY);return history.filter(item=>new Date(item.cookedAt)>=cutoff)}
export function countTags(history,meals,now=new Date()){const map=new Map(meals.map(m=>[m.id,m])),counts={};for(const entry of weekEntries(history,now)){const meal=map.get(entry.mealId);if(!meal)continue;for(const tag of meal.tags)counts[tag]=(counts[tag]||0)+1}return counts}
export function healthNudge(history,meals,now=new Date()){const counts=countTags(history,meals,now);if(!weekEntries(history,now).length)return'هنوز داده کافی ندارم. اولین وعده را ثبت کن تا پیشنهادها دقیق‌تر شوند.';if(!counts.fish)return'این هفته هنوز ماهی ثبت نشده؛ اگر برایت مناسب است، یک وعده ماهی می‌تواند تنوع خوبی ایجاد کند.';if((counts.legume||0)<2)return'حبوبات این هفته کم بوده؛ عدسی، آش یا فلافل می‌تواند انتخاب خوبی باشد.';if((counts.vegetable||0)<2)return'سهم سبزیجات این هفته پایین است؛ یک وعده سبزیجات‌محور انتخاب کن.';if((counts.red_meat||0)>=3)return'گوشت قرمز چند بار تکرار شده؛ بهتر است وعده بعدی مرغ، ماهی، حبوبات یا غذای گیاهی باشد.';return'تنوع این هفته خوب است؛ وعده بعدی را بر اساس فاصله از آخرین پخت انتخاب می‌کنم.'}
function daysSince(date,now){return(now-new Date(date))/DAY}
export function scoreMeal(meal,history,meals,mode='default',now=new Date()){let score=50;const last=history.find(h=>h.mealId===meal.id);if(!last)score+=24;else score+=Math.min(22,Math.max(-24,daysSince(last.cookedAt,now)*3-12));const recent3=history.slice(0,3).map(h=>meals.find(m=>m.id===h.mealId)).filter(Boolean);for(const recent of recent3){if(recent.tags.some(tag=>meal.tags.includes(tag)&&['rice','red_meat','chicken','fish','legume','egg'].includes(tag)))score-=7}const weekly=countTags(history,meals,now);if(!weekly.fish&&meal.tags.includes('fish'))score+=16;if((weekly.legume||0)<2&&meal.tags.includes('legume'))score+=9;if((weekly.vegetable||0)<2&&meal.tags.includes('vegetable'))score+=7;if((weekly.red_meat||0)>=2&&meal.tags.includes('red_meat'))score-=14;if(mode==='quick')score+=meal.minutes<=40?24:-18;if(mode==='budget')score+=meal.cost<=2?22:-10;if(mode==='healthy')score+=meal.tags.includes('healthy')?20:0;return score}
export function recommendMeal(meals,history,mode='default',excludedIds=[],now=new Date()){const candidates=meals.filter(m=>!excludedIds.includes(m.id));if(!candidates.length)return meals[0];const ranked=candidates.map(meal=>({meal,score:scoreMeal(meal,history,meals,mode,now)})).sort((a,b)=>b.score-a.score),top=ranked.slice(0,Math.min(3,ranked.length)),total=top.reduce((sum,x)=>sum+Math.max(1,x.score),0);let roll=Math.random()*total;for(const item of top){roll-=Math.max(1,item.score);if(roll<=0)return item.meal}return top[0].meal}
export function recommendationReason(meal,history,meals,mode='default'){if(mode==='quick')return'انتخاب سریع';if(mode==='budget')return'انتخاب اقتصادی';if(mode==='healthy')return'برای تنوع متعادل‌تر';const weekly=countTags(history,meals);if(!weekly.fish&&meal.tags.includes('fish'))return'نوبت ماهی رسیده';if((weekly.legume||0)<2&&meal.tags.includes('legume'))return'حبوبات این هفته کم بوده';if(!history.some(h=>h.mealId===meal.id))return'مدتی است در برنامه نبوده';return'بر اساس تاریخچه اخیر'}
